DronMDF/zold-lazy-node

node/app.py, test/zold/test_score.py, zold/score.py
Сюда вошла отдача всех скоров для рассчета майнинга.
=> #41: ScoreHash object

node/app.py, node/score.py
=> #66: Устаревание Score

zln/zln.py, zold/score.py
Помимо консольного приложения этот класс очень нужен в тестах.
Чтобы формировать валидные Score нужного уровня.
=> #65: MinedScore для выработки новых суффиксов

node/score.py, test/node/test_score.py
Пока еще не заработало...
Какие-то проблемы в этом тесте с инициализацией app.
=> #76: Формирование корректного prefix

ansible/roles/gunicorn/tasks/main.yml, ansible/roles/nginx/templates/nginx.j2
Перезапуск помогает это обойти.
Хотя мне так и не удалось сделать корректный перезапуск.
=> #113: Перезапуск сервиса в процессе заливки

node/app.py, node/wallet.py, requirements.txt, test/node/test_get_tasks.py, test/node/test_wallet.py
=> #139: Задание на поиск кошелька

node/app.py, node/db.py, node/transaction.py, node/wallet.py, zold/transaction.py, zold/wallet.py
Эту задачу отдельно не потестируешь,
будем тестировать вместе с вливанием транзакций.
=> #153: Формирование кошелька из транзакций

node/app.py, node/transaction.py, test/node/test_put_wallet.py, zold/transaction.py
=> #156: Подтверждение транзакций получателем

test/node/test_transaction.py, zold/transaction.py
=> #172: Общий код для подписываемого содержимого транзакции

node/app.py, node/wallet.py, test/node/test_get_tasks.py, test/node/test_put_wallet.py, zold/wallet.py
Это изменение пока не заработало, я не понял почему...
При этом я уперся в длину модуля node.app и надо думать, как это разрулить.
И pdd почему-то не работает, поэтому продолжаю колбасить тикет #155 
Здесь можно к примеру написать не процедурно, а оопшненько
for tnx in NewTransactions(IncomingTransactions(wallet.transactions()), DbTransactions.incoming(wallet.id())):
И отфильтровать в итераторе...
=> #155: Имеющиеся транзакции не нуждаются в поиске

node/app.py, zln/zln.py
=> #141: Майнинг на основе информации из /tasks

node/app.py, node/score.py, zold/score.py, zold/score_props.py
Начал продвигать в среду Score новый подход, который заключается в том,
что Score отдает то, из чего состоит. Для различных видов упаковки
существуют отдельные классы. ScoreString, ScoreJson и тд...
=> #175: Класс обертка - score сервера

zln/zln.py
=> #149: Теперь отсутствие поля в заголовке приравнивается к LowScore

node/score.py, zold/score.py
@aatsurkan Need review
Разгребаю пока по мелочам.
=> #178: MainScore делегирует запросы инкапсулированному Score

node/app.py, node/transaction.py, test/node/test_get_wallet.py
=> #183: Подтверждение входящих платежей перед получением кошелька

node/app.py, test/node/test_get_tasks.py
@aatsurkan Need review
Что ж мне никто не сказал, что у меня там куча print?
=> #185: Поиск от ремотов тоже называется wanted

node/wallet.py, test/node/test_transaction.py, zln/zln.py, zold/transaction.py, zold/wallet.py
@aatsurkan Синхронизация идет, база уже выросла до 300 кошельков...
Но помоему она немного ходит по кругу... всего кошелков 14 тысяч..
Надо еще пофиксить некоторые проблемы.
=> #187: Синхронизация кошельков

node/app.py, test/node/test_get_tasks.py, test/node/test_get_wallet.py, test/node/test_put_wallet.py, test/node/test_transaction.py, test/node/test_wallet.py, test/zold/test_transaction.py
=> Очистка заданий из tasks

node/app.py, test/node/test_get_tasks.py
=> #196: Контроль содержимого wanted, Нет дублирований

node/app.py, test/node/test_get_root.py
=> #199: Дополнительный заголовок формируется самим приложением

node/app.py, test/node/test_get_wallet.py
=> #204: Время модификации кошелька

node/app.py, node/wallet.py, test/node/test_get_root.py
=> #132: Количество кошельков

node/app.py, node/transaction.py, test/node/test_get_tasks.py
@aatsurkan Need review
С сервером некоторые проблемы. я расчистил его, и теперь вижу, что некоторые из базовых транзакций невалидны.. Причем они невалидны и в zold... Поэтому надо их игнорить...
Возможно придется еще что-то подчистить в БД.
Возможно, пока у меня было дублирование, я позволил себе принять больше транзакций, чем следовало. :)
=> #195: Информация об инициаторах поиска в tasks

node/transaction.py
За счет более быстрой проверки наличия транзакций в БД
=> #214: Ускорение приема кошельков

node/app.py, test/node/test_get_wallet.py
=> #223: Баланс кошелька

node/transaction.py, test/node/test_put_wallet.py
=> #225: Расходование последних средств

node/app.py, test/node/test_put_wallet.py
=> #48 Проверка данных входящего кошелька
